# Generated by Django 5.1.1 on 2024-09-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20240919_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.doctor')),
                ('procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.procedure')),
            ],
            options={
                'unique_together': {('procedure_id', 'doctor_id')},
            },
        ),
    ]
