# Generated by Django 5.1.1 on 2024-09-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_doctor_specialty_doctorspecialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.appointment')),
                ('procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.procedure')),
            ],
        ),
    ]
