# Generated by Django 5.1.1 on 2024-09-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_appointmentprocedure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentprocedure',
            unique_together={('procedure_id', 'appointment_id')},
        ),
    ]
