# Generated by Django 5.1.1 on 2024-09-15 07:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_doctorclinicaffiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=200)),
                ('street_address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats 12345 or 12345-1234', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')])),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='state',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='doctorclinicaffiliation',
            name='clinic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.clinic'),
        ),
        migrations.AlterField(
            model_name='doctorclinicaffiliation',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.doctor'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.address'),
        ),
    ]
