# Generated by Django 5.1.1 on 2024-09-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_doctorschedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.clinic')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.patient')),
            ],
        ),
    ]
